Add option to define rel property for page number anchor tag
AdeleD/react-paginate pull request #391
Opened 2021-11-02 15:37 UTC by switzbug

The following changes add the 'rel' property to the page number anchor tag.

By default, it assigns the 'rel' property of 'canonical' to the selected page. The page just before the selected page and page just after the selected page is assigned the 'rel' property of value 'prev' and  'next'  respectively. The rest of the pages are not assigned 'rel' property.

This change will be an improvement for SEO.
It solves #386.

2021-11-02 18:43 UTC, MonsieurV requested changes
Thanks for the PR @switzbug :)

Only few little changes and this is good for me.

2021-11-02 18:43 UTC, MonsieurV commented on __tests__/PaginationBoxView-test.js
> +    it('should not render prevPageRel if the break page is present just before the selected page', function () {
Aren't these 2 tests description inverted?

On this one it says _should **not** render **prevPageRel**_, but then we find the `prev` rel.

2021-11-02 18:43 UTC, MonsieurV commented on react_components/PaginationBoxView.js
> +    prevPageRel: PropTypes.string,
As these are new props, can their description be added in the `README.md`?

2021-11-02 18:43 UTC, MonsieurV commented on react_components/PaginationBoxView.js
> +        rel={this.handlePageRel(index)}
This may be more pertinently named `getElementPageRel` then _handle_, because we generate a value and do not handle any event here.

2021-11-02 18:44 UTC, MonsieurV commented on __tests__/PaginationBoxView-test.js
> +    it('should render default rel if not defined', function () {
Last request: add a test to ensure we can disable the `rel` all together by setting them to `undefined`

2021-11-03 05:48 UTC, switzbug commented
Hi @MonsieurV. I have made all the requested changes. 
I have doubt about the last change - 

> add a test to ensure we can disable the rel altogether by setting them to undefined.

 I am not able to disable `rel` bypassing `undefined` but bypassing `null`.
Please let me know if this is okay. Also, should I add this to README.md?

2021-11-03 06:45 UTC, switzbug commented
Closed by mistake.

2021-11-03 15:25 UTC, merged